version: "3.4"

services: 
    auth:
        build: ./auth
        image: auth:latest
        env_file: ./auth/postgres.env
        depends_on:
            - auth-db
        ports:
            - "5000"
        restart: always
    auth-db:
        image: postgres:latest
        env_file: ./auth/postgres.env
        restart: always
    # frontend:
    #     build: ./front
    #     image: front:latest
    #     ports:
    #         - "3000"
    #     environment:
    #         - NODE_ENV=development
    #         - REACT_APP_SERVICE_URL=http://localhost:80
    #         - CHOKIDAR_USEPOLLING=true
    #     depends_on:
    #         - auth
    #     restart: always
    # backend:
    #     build: ./backend
    #     image: backend:latest
    #     ports:
    #         - "5001"
    #     depends_on:
    #         - backend-db
    #     restart: always
    # backend-db:
    #     image: redis:latest
    #     restart: always
    # nginx:
    #     build: ./nginx
    #     image: nginx:latest
    #     ports:
    #         - 80:80
    #     depends_on:
    #         - auth
    #         - front
    #         - back