version: "3.4"

services: 
    keyrock:
        container_name: keyrock
        build: ./keyrock     
        image: keyrock:latest
        hostname: keyrock
        depends_on:      
            - mysql-db     
        ports:      
            - '3001:3001'      
            - '443:443'    
        networks:      
            default-1:         
                ipv4_address: 172.18.1.21
        restart: always
    mysql-db:
        restart: always
        image: mysql:5.7
        hostname: mysql-db
        container_name: db-mysql
        expose:
            - '3306'
        ports:
            - '3306:3306'
        networks:
            default-1:
                ipv4_address: 172.18.1.20
        environment:
            # Development use only
            # Use Docker Secrets for Sensitive Data
            - 'MYSQL_ROOT_PASSWORD=secret'
            - 'MYSQL_ROOT_HOST=172.18.1.21'
        volumes:
            - mysql-db:/var/lib/mysql
    # pep-proxy:
    #     build: ./pep-proxy
    #     image: pep-proxy:latest
    #     ports:
    #         - "1027"
    #     networks:
    #         - default-1
    #     restart: always
    orion-mongo:
        container_name: db-orion
        image: mongo:3.4
        command: --nojournal
        networks:
            - default-1
        volumes:
            - orion-mongo:/var/lib/mongo
    orion:
        container_name: orion
        image: fiware/orion
        ports:
            - "1026:1026"
        command: -dbhost orion-mongo
        networks:
            - default-1
    front:
        container_name: reactjs
        build: ./front
        image: front:latest
        ports:
            - "3000"
        environment:
            - NODE_ENV=development
            - REACT_APP_SERVICE_URL=http://localhost:80
            - IDM_APP_CLIENT_ID='02b213e7-f627-4ab5-9afb-886f8e89e756'
            - IDM_APP_CLIENT_SEC='5b17f806-f37b-4804-a72d-e0c256e1f252'
            - CHOKIDAR_USEPOLLING=true
        depends_on:
            - keyrock
        networks:
            - default-1
        # restart: always
    data-storage:
        container_name: flask
        build: ./data-storage
        image: data-storage:latest
        env_file: ./data-storage/databases.env
        depends_on:
            - ds-mongo
        ports:
            - "5001"
        networks:
            - default-1
        restart: always
    ds-mongo:
        container_name: flask-db
        image: mongo
        restart: always
        networks:
            - default-1
        volumes:
            - ds-mongo:/var/lib/mongo
    # fav-db:
    #     image: redis:latest
    #     env_file: ./back/databases.env
    #     networks:
    #         - default-1
    #     # restart: always
    nginx:
        container_name: nginx
        restart: always
        build: ./nginx
        image: nginx:latest
        ports:
            - 80:80
        depends_on:
            - keyrock
            - front
            - data-storage
        networks:
            - default-1
networks:
    default-1:
        ipam:
            config:
                - subnet: 172.18.1.0/24
volumes:
    mysql-db: ~
    ds-mongo: ~
    orion-mongo: ~
